name: Actions 😎

on: [push, pull_request]

jobs:
  release-project:
  name: Release Project
  runs-on: ubuntu-latest
  needs: build
  steps: 
    - uses: actions/download-artifact@v3
      with:
        name: Build
        path: build
    - name: ZIP Build
      uses: thedoctor0/zip-release@master
      with: 
        filename: build.zip
    - name: Bump version and push tag
      id: newTag
      uses: hennejg/github-tag-action@v4.1.jh1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{steps.newTag.outputs.new_tag}}
        release_name: Release ${{steps.newTag.outputs.new_tag}}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false


  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          allowDirtyBuild: true


        # Output
        - uses: actions/upload-artifact@v3
          with:
            name: Build
            path: build
